spring:
  main:
    allow-bean-definition-overriding: true
  hikari:
    datasource:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://192.168.123.101:3306/batch_repo?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: cat
      password: Ckth1735!@



batch:
  job:
    cron: 0 */5 * * * *
    names: ${job.name:NONE}

mybatis:
  mapper-locations: classpath:mapper/*.xml
