spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.123.101:3306/batch_repo?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: cat
    password: Ckth1735!@

  sql:
    init:
      mode: never
      schema-locations: classpath:schema-mysql.sql


mybatis:
  mapper-locations: classpath:/mapper/*.xml

