spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch_repo?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: batch_user
    password: password

  batch:
    jdbc:
      initialize-schema: always