/* CRUD 예제 테이블, 영속성 컨텍스트 예제 테이블 */
CREATE TABLE MEMBER(
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    AGE INTEGER NOT NULL,
    PRIMARY KEY (ID)
)

/* 엔티티 매핑 예제 테이블  */
CREATE TABLE MEMBER(
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    AGE INTEGER,
    ROLE_TYPE VARCHAR(255),
    CREATE_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP,
    DESCRIPTION BLOB,
    PRIMARY KEY (ID)
)

/* Key Strategy 예제 테이블 */
CREATE TABLE BOARD(
    ID BIGINT NOT NULL PRIMARY KEY,
    DATA VARCHAR(255)
)
/* 시퀀스 생성 */
CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1;
/* 테이블 전략 */
CREATE TABLE MY_SEQUENCES(
    SEQUENCE_NAME VARCHAR(255) NOT NULL,
    NEXT_VAL BIGINT,
    PRIMARY KEY (SEQUENCE_NAME)
)



/* TABLE Mapping 예제 테이블 */
CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR(255) NOT NULL,
    TEAM_ID VARCHAR(255),
    USERNAME VARCHAR(255),
    PRIMARY KEY (MEMBER_ID)
)

CREATE TABLE TEAM(
    TEAM_ID  VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    PRIMARY KEY (TEAM_ID)
)
/* 외레키 제약조건 */
ALTER TABLE MEMBER ADD CONSTRAINT FK_MEMBER_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM