server:
  port: 8000

spring:
  application:
    name: gatewayservice
#  cloud:
#    gateway:
#      routes:
#        - id: first-service
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/first-service/**
#        - id: second-service
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/second-service/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-uri:
      default-Zone: http://localhost:8761/eureka
