spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:tcp://localhost/D:/JPAProject/test
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver


logging.level:
  org.hibernate.SQL: debug